services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: threaddb
      MYSQL_ROOT_PASSWORD: PasswordBaruAnda
      MYSQL_USER: thread_user
      MYSQL_PASSWORD: PasswordBaruAnda
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://thread_user:PasswordBaruAnda@db:3306/threaddb
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - TWITTER_CLIENT_ID=${TWITTER_CLIENT_ID}
      - TWITTER_CLIENT_SECRET=${TWITTER_CLIENT_SECRET}
      - FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
    depends_on:
      - db

volumes:
  mysql_data:
